### ISSUE TITLE
BFM point color should be multiply by the color coefficient?

### ISSUE THREAD

**Issue by hastaluegoph** [TimoBolkart/BFM_to_FLAME#1]
Thanks for a great work ! It's brilliant to transfer the uv basis of FLAME from BFM. I have a problem here, for calculate the point color, should it multiply by the color coefficient? I  found that part is exactly same with the mean color calculation.
![Snipaste_2020-12-17_00-06-53](https://user-images.githubusercontent.com/33288604/102375447-7f4d9a00-3ffd-11eb-9937-27ec6d62a0ff.png)

**Comment by TimoBolkart** [comment]
That part computes the color of a pixel by Barycentric coordinates. The Barycentric coordinates however do not change, that's why the code is the same for both. However the `bfm_verts_color` for a particular component differs from the mean computation. Just print the values of `bfm_verts_color` for the mean and tehn for each of the components inside the for loop. You will see that it changes. Does that answer your question?

**Comment by hastaluegoph** [comment]
yes, that answer my question! I just check the colors values, it does change every iteration by setting the color_coeffs. Thanks for your help and patience!
